[[constraint]]
  name = "github.com/golang/mock"
  version = "1.1.1"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.2"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "0.9.1"